# Generated by Django 4.0.2 on 2022-03-09 14:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_alter_message_senttime_alter_project_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='sentTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 9, 14, 34, 23, 929557), verbose_name='time sent'),
        ),
        migrations.AlterField(
            model_name='project',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 9, 14, 34, 23, 929557), verbose_name='date published'),
        ),
    ]
