# Generated by Django 4.0.2 on 2022-03-10 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_client_user_alter_message_senttime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sentTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 10, 16, 36, 20, 659592), verbose_name='time sent'),
        ),
        migrations.AlterField(
            model_name='project',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 10, 16, 36, 20, 659592), verbose_name='date published'),
        ),
    ]
