# Generated by Django 4.0.2 on 2022-03-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_message_senttime_alter_project_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sentTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
