# Generated by Django 4.0.2 on 2022-03-08 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=60)),
                ('surname', models.CharField(default=' ', max_length=60)),
                ('developer', models.BooleanField(default=False)),
                ('university', models.CharField(default='', max_length=60)),
                ('company', models.CharField(default='', max_length=60)),
                ('biography', models.TextField(default='', max_length=750)),
                ('emailAddress', models.EmailField(default='', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_description', models.CharField(default='h', max_length=150)),
                ('long_description', models.CharField(max_length=750)),
                ('salary', models.IntegerField()),
                ('expectedDuration', models.CharField(default='1 day', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ON GOING', 'On going'), ('FINISHED', 'Finished')], default='PENDING', max_length=8)),
                ('developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='developing_project', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_project', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
