# Generated by Django 4.0.2 on 2022-03-09 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 9, 10, 43, 58, 587080), verbose_name='date published'),
        ),
    ]
