# Generated by Django 4.0.2 on 2022-03-10 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_message_senttime_alter_project_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sentTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 10, 17, 21, 26, 88221), verbose_name='time sent'),
        ),
        migrations.AlterField(
            model_name='project',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 10, 17, 21, 26, 88221), verbose_name='date published'),
        ),
    ]
